name: CI

on:
  push:
    branches: ["**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build libgtest-dev
      - name: Build
        run: |
          cmake -B build -DWITH_ASAN=ON -G Ninja
          cmake --build build
      - name: Test
        run: |
          cd build && ctest --output-on-failure
